---
services:
  rails:
    build:
      context: .
      args:
        RAILS_ENV: development
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    command: bundle exec rails s -b 0.0.0.0

volumes:
  bundle:
